package quizme.model;

import java.util.Date;
import java.util.List;

import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.PrimaryKey;

import quizme.utils.ObjectifyUtils;

import com.google.appengine.datanucleus.annotations.Unowned;
import com.googlecode.objectify.Ref;
import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Index;
import com.googlecode.objectify.annotation.Load;

@PersistenceCapable
@Entity
@Index
public class Question {

	@PrimaryKey
    @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
	@Id
	// Id generated by datastore
	private Long id;
	
	@Persistent
	// Date on which this was created
	private Date createdDate;
	
	@Persistent
	@Unowned
	@Load
	// Subject to which this belongs (E.g., science, match, religion)
	private Ref<Classification> subject;
	
	@Persistent
	@Unowned
	@Load
	// Category (E.g., Zoology, Calculus, Hinduism)
	private Ref<Classification> category;
	
	@Persistent
	@Unowned
	@Load
	// Sub-category (E.g., Integral calculus, Protestant, Catholic)
	private Ref<Classification> subCategory;
	
	@Persistent
	// Searchable text
	private String tags;
	
	@Persistent
	@Load
	// User who created this
	private Ref<AppUser> user;
	
	@Persistent
	// Type of question
	private QuestionType type;
	
	@Persistent
	// Difficulty level
	private DifficultyLevel level;
	
	@Persistent
	@Unowned
	@Load
	// Group this belongs to 
	private Ref<UserGroup> group;
	
	@Persistent
	@Load
	// Details about this
	private Ref<MultiPartContent> details;
	
	@Persistent
	@Load
	// Actual content
	private Ref<MultiPartContent> content;
	
	// Options
	@Load
	private List<Ref<Option>> options;
	
	public Question() {
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Classification getCategory() {
		return category.get();
	}
	
	public void setCategory(Classification category) {
		this.category = Ref.create(category);
	}
	
	public Classification getSubCategory() {
		return subCategory.get();
	}
	
	public void setSubCategory(Classification subCategory) {
		this.subCategory = Ref.create(subCategory);
	}
	
	public Classification getSubject() {
		return subject.get();
	}
	
	public void setSubject(Classification subject) {
		this.subject = Ref.create(subject);
	}

	public String getTags() {
		return tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public AppUser getUserId() {
		return user.get();
	}
	
	public void setUserId(AppUser _user) {
		this.user = Ref.create(_user);
	}

	public QuestionType getType() {
		return type;
	}

	public void setType(QuestionType type) {
		this.type = type;
	}

	public DifficultyLevel getLevel() {
		return level;
	}

	public void setLevel(DifficultyLevel level) {
		this.level = level;
	}
	
	public UserGroup getGroup() {
		return group.get();
	}
	
	public void setGroup(UserGroup group) {
		this.group = Ref.create(group);
	}	
	
	public MultiPartContent getContent() {
		return content.get();
	}
	
	public void setContent(MultiPartContent content) {
		this.content = Ref.create(content);
	}
	
	public MultiPartContent getDetails() {
		return details.get();
	}
	
	public void setDetails(MultiPartContent details) {
		this.details = Ref.create(details);
	}
	
	public List<Option> getOptions() {
		return ObjectifyUtils.getDomainList(options);
	}
	
	public void setOptions(List<Option> options) {
		this.options = ObjectifyUtils.getRefList(options);		
	}
}
